---
title: "Reproducible Research Final Project"
author: "Erim Celen, Ozgur Polat, Bugra Duman"
date: "5/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(readr)
library(tidyverse)
library(dplyr)
library(kableExtra)
library(caret)
library(nnet)
```

```{r message=FALSE, warning=FALSE, include=FALSE}
data <- read_csv("C:\\Users\\Bugra\\Documents\\GitHub\\Reproducible-Research-Final-Project\\Data\\E0.csv")
```

```{r echo=FALSE}
table <- data %>% 
            summarise('Home Team Shots' = sum(HS), 
                      'Home Team Shots on Target' = sum(HST), 
                      'Away Team Shots' = sum(AS), 
                      'Away Team Shots on Target' = sum(AST)) %>% 
            pivot_longer(everything())

table <- table %>% 
            mutate(place = substr(name,1,4))

ggplot(table, aes(x=name, y=value, fill=place)) + 
  geom_bar(stat = "identity") +
  geom_text(aes(label = value)) +
  theme(axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        axis.text.y = element_blank(),
        axis.ticks.y = element_blank(),
        legend.title = element_blank())

```

```{r include=FALSE}
proportions <- as.data.frame(c("Home","Away")) %>% setNames(c("name"))
proportions$value <- c(round(table[2,2] / table[1, 2],4) * 100,round(table[4,2] / table[3, 2],4) * 100)
proportions$value = paste0('%', proportions$value)
```

```{r echo=FALSE}
proportions %>%
  kable(col.names = NULL,digits = 2,"html",row.names = FALSE,caption = "Percentage of Shots on Target") %>%
  kable_styling(font_size = 20,bootstrap_options = c("striped"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>%
  group_by(Time) %>%
  tally(sort = T) %>%
  top_n(3) %>%
  kable(col.names = NULL,digits = 2,"html",row.names = FALSE,caption = "Most Played Game Hours") %>%
  kable_styling(font_size = 20,bootstrap_options = c("striped"))
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
data %>% 
  mutate(FTR = as_factor(FTR)) %>%
  mutate(FTR = recode_factor(FTR,A = "Away", H = "Home", D = "Draw")) %>%
  group_by(FTR) %>%
  count() %>%
  kable(col.names = NULL,digits = 2,"html",row.names = FALSE,caption = "Full Time Results") %>%
  kable_styling(font_size = 20,bootstrap_options = c("striped"))
```

```{r}
#most crucial referees
data %>%    filter(HR >0 | AR > 0 | HY>0 | AY>0) %>% count(Referee)
```
```{r}



#needs to updated not every file ends with 16th column
res <- cor(data[c("FTHG","FTAG","HTHG","HTAG","HS","AS","HST","AST","HF","AF","HC","AC","HY","AY","HR","AR")])

ggcorrplot::ggcorrplot(res,type="lower",hc.order=TRUE,method='circle')
```

```{r Model}

data$Date <- lubridate::mdy(data$Date)
data$Time <- hms::as_hms(data$Time)
data$FTR <- as.factor(data$FTR)
data$HTR <- as.factor(data$HTR)

data <- data %>% mutate(FTR= relevel(FTR,ref='H'),
                        HTR=relevel(HTR,ref='H'))

index<- createDataPartition(data$FTR,p=.70,list = FALSE)

train <- data[index,]
test<- data[-index,]




multinom_mod<- multinom(FTR ~ . ,data=train[c("FTR","HTR","FTHG","FTAG","HTHG","HTAG","HS","AS","HST","AST","HF","AF","HC","AC","HY","AY","HR","AR")])



```

```{r}


HomeBet <-data %>%  filter(FTR == "H") %>% 
  select("Date","HomeTeam","AwayTeam","FTR","B365H","BWH","IWH","PSH","WHH","VCH")


HomeBet$Max <- pmax(HomeBet$B365H,HomeBet$IWH,HomeBet$PSH,HomeBet$WHH,HomeBet$VCH)

AwayBet <-data %>%  filter(FTR == "A") %>% 
  select("Date","HomeTeam","AwayTeam","FTR","B365A","BWA","IWA","PSA","WHA","VCA")

AwayBet$Max <- pmax(AwayBet$B365A,AwayBet$IWA,AwayBet$PSA,AwayBet$WHA,AwayBet$VCA)
AwayBet

```

